parameters:
    presta_cms.page.factory.class: Presta\CMSSandboxBundle\Factory\PageFactory

presta_cms_core:
    default_website: /website/sandbox
    default_locale: en
    websites:
        sandbox:
            path: /website/sandbox
            hosts:
                dev:
                    en:
                        locale: en
                        host: sandbox-prestacms.dev
                    fr:
                        locale: fr
                        host: sandbox-prestacms.fr.dev
                prod:
                    en:
                        locale: en
                        host: sandbox.prestacms.com
                    fr:
                        locale: fr
                        host:  sandbox.prestacms.fr
                jenkins:
                    en:
                        locale: en
                        host: sandbox-prestacms.loc
                integration:
                    en:
                        locale: en
                        host:  en.prestacms-sandbox.integration54.local
                    fr:
                        locale: fr
                        host:  fr.prestacms-sandbox.integration54.local