sandbox_service:
    resource: "@SandboxServiceBundle/Controller/"
    type:     annotation
    prefix:   /

#Sonata Admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#override sonata routes
sonata_admin_dashboard:
    pattern: /admin
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

PrestaCMSCoreBundle:
    resource: "@PrestaCMSCoreBundle/Resources/config/routing.yml"
    prefix:   /admin

phpcrodmbrowser:
    resource: @SonataDoctrinePHPCRAdminBundle/Resources/config/routing/phpcrodmbrowser.xml
    prefix: /admin/browser

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
