
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN:
          - ROLE_ALLOWED_TO_SWITCH
          - ROLE_ADMIN
        ROLE_ADMIN:
          - ROLE_ADMIN_USER
          - ROLE_ADMIN_MEDIA
          - ROLE_ADMIN_CMS
          - ROLE_ADMIN_CMS_ACCESS

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # -> custom firewall for the admin area of the URL
        admin:
            pattern:      /admin/(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    false
                check_path:     sonata_user_admin_security_check
                failure_path:   null
                always_use_default_target_path: true
                default_target_path: /admin

            logout:
                path:           sonata_user_admin_security_logout
                target:         sonata_user_admin_security_login
            anonymous:    true
        # -> end custom configuration

        # defaut login area for standard users
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /user/login
                use_forward:    false
                check_path:     /user/login_check
                failure_path:   null
            logout:
                path: /user/logout
            anonymous:    true


    # ...
    access_control:

        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> custom access control for the admin area of the URL
        - { path: ^/admin/[a-z][a-z]/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/[a-z][a-z]/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/[a-z][a-z]/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: /admin/, role: [ROLE_ADMIN_CMS_ACCESS] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
    # ...
